name: "Auto Deploy"

on:
  push:
    tags:
      - "auto-deploy/v*"

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4


      - name: Create Release
        uses: ncipollo/release-action@v1.16.0
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          
